# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekdays',
            name='lecturers',
        ),
        migrations.AddField(
            model_name='weekdays',
            name='lect_name',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='weekdays',
            name='lect_room',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
