# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0002_auto_20170520_1326'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weekdays',
        ),
    ]
