# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 14:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0009_lecturers_weekdays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lecturers',
        ),
        migrations.DeleteModel(
            name='Weekdays',
        ),
    ]
