# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0013_lecturer_weekday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='lecturer',
        ),
        migrations.DeleteModel(
            name='Lecturer',
        ),
        migrations.DeleteModel(
            name='Weekday',
        ),
    ]
