# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule_app', '0020_auto_20170520_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('classroom', models.CharField(max_length=200)),
            ],
        ),
    ]
