# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule_app', '0021_lecturer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_name', models.CharField(max_length=200)),
                ('lecturer', models.ManyToManyField(to='schedule_app.Lecturer')),
            ],
        ),
    ]
